sudo: false
language: ruby

install: make

rvm:
  - "2.5"

before_install:
  - gem update --system
  - gem --version

stages:
  - test
  - build
  - publish

jobs:
  include:
    - stage: test
      name: "Run unit tests"
      script: make test

    - stage: build
      name: "Build the docker image"
      script: exit 0
      if: branch = master

    - stage: publish
      name: "Publish the application image to ECR"
      script: exit 0
      if: branch = master AND tag IS present

