sudo: required
language: generic

services:
  - docker
  - postgresql

stages:
  - test
  - build
  - publish

jobs:
  include:
    - stage: test
      name: "Run unit tests"
      before_script:
        - psql -c 'CREATE DATABASE sinatra;' -U postgres
        - psql -c 'CREATE TABLE users (id SERIAL, name VARCHAR(255), surname VARCHAR(255), age INT);' -U postgres -d sinatra
      script:
        - make install
        - make test
      env:
        - PG_HOST=localhost
        - PG_PORT=5432
        - PG_USER=postgres
        - PG_DBNM=sinatra

    - stage: build
      name: "Build the docker image"
      script:
        - docker build -t $APPLICATION_NAME .
      if: branch = master OR tag is present

    - stage: publish
      name: "Publish the application image to ECR"
      script:
        - pip install awscli --user
        - export PATH=$PATH:$HOME/.local/bin
        - eval $(aws ecr get-login --no-include-email --region us-east-1)
        - docker build -t $APPLICATION_NAME .
        - docker tag $APPLICATION_NAME:latest $ECR_REPOSITORY_URL/$APPLICATION_NAME:$TRAVIS_TAG
        - docker push $ECR_REPOSITORY_URL/$APPLICATION_NAME:$TRAVIS_TAG
      if: tag IS present
