sudo: required
language: generic

services:
  - docker
  - postgresql

stages:
  - test
  - build
  - publish

jobs:
  include:
    - stage: test
      name: "Run unit tests"
      before_script:
        - psql -c 'CREATE DATABASE sinatra;' -U postgres
        - psql -c 'CREATE TABLE users (id SERIAL, name VARCHAR(255), surname VARCHAR(255), age INT);' -U postgres -d sinatra
      script:
        - gem install bundler
        - bundle install
        - ruby ./test/app_test.rb
      env:
        - PG_HOST=localhost
        - PG_PORT=5432
        - PG_USER=postgres
        - PG_DBNM=sinatra

    - stage: build
      name: "Build the docker image"
      script:
        - docker --version
        - docker build -t ${APPLICATION_NAME} .
      if: branch = master

    - stage: publish
      name: "Publish the application image to ECR"
      script:
        - pip3 install awscli --user
        - export PATH=$PATH:$HOME/.local/bin
        - export AWS_ACCOUNT_ID="$( aws sts get-caller-identity --output text --query 'Account' )"
        - eval $(aws ecr get-login --region us-east-1)
        - docker tag ${APPLICATION_NAME}:${TRAVIS_TAG} 123456789012.dkr.ecr.us-east-1.amazonaws.com/${APPLICATION_NAME}:${TRAVIS_TAG}
      if: branch = master AND tag IS present

